# Generated by Django 5.0.4 on 2024-05-15 14:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0003_profile_date_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_modified",
            field=models.DateField(
                auto_now=True, verbose_name=django.contrib.auth.models.User
            ),
        ),
    ]
