# Generated by Django 5.0.4 on 2024-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0005_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
